/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsWebhooksRouteImport } from './routes/settings.webhooks'
import { Route as SettingsRecommendationsRouteImport } from './routes/settings.recommendations'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsMultistreamRouteImport } from './routes/settings.multistream'
import { Route as SettingsFavouritesRouteImport } from './routes/settings.favourites'
import { Route as ChannelHandleRouteImport } from './routes/channel.$handle'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRecommendationsRoute = SettingsRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMultistreamRoute = SettingsMultistreamRouteImport.update({
  id: '/multistream',
  path: '/multistream',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFavouritesRoute = SettingsFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => SettingsRoute,
} as any)
const ChannelHandleRoute = ChannelHandleRouteImport.update({
  id: '/channel/$handle',
  path: '/channel/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/channel/$handle': typeof ChannelHandleRoute
  '/settings/favourites': typeof SettingsFavouritesRoute
  '/settings/multistream': typeof SettingsMultistreamRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/recommendations': typeof SettingsRecommendationsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/settings/favourites': typeof SettingsFavouritesRoute
  '/settings/multistream': typeof SettingsMultistreamRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/recommendations': typeof SettingsRecommendationsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/go-live': typeof GoLiveRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/channel/$handle': typeof ChannelHandleRoute
  '/settings/favourites': typeof SettingsFavouritesRoute
  '/settings/multistream': typeof SettingsMultistreamRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/recommendations': typeof SettingsRecommendationsRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/go-live'
    | '/login'
    | '/search'
    | '/settings'
    | '/channel/$handle'
    | '/settings/favourites'
    | '/settings/multistream'
    | '/settings/profile'
    | '/settings/recommendations'
    | '/settings/webhooks'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/go-live'
    | '/login'
    | '/search'
    | '/channel/$handle'
    | '/settings/favourites'
    | '/settings/multistream'
    | '/settings/profile'
    | '/settings/recommendations'
    | '/settings/webhooks'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/go-live'
    | '/login'
    | '/search'
    | '/settings'
    | '/channel/$handle'
    | '/settings/favourites'
    | '/settings/multistream'
    | '/settings/profile'
    | '/settings/recommendations'
    | '/settings/webhooks'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GoLiveRoute: typeof GoLiveRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ChannelHandleRoute: typeof ChannelHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/webhooks': {
      id: '/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/recommendations': {
      id: '/settings/recommendations'
      path: '/recommendations'
      fullPath: '/settings/recommendations'
      preLoaderRoute: typeof SettingsRecommendationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/multistream': {
      id: '/settings/multistream'
      path: '/multistream'
      fullPath: '/settings/multistream'
      preLoaderRoute: typeof SettingsMultistreamRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/favourites': {
      id: '/settings/favourites'
      path: '/favourites'
      fullPath: '/settings/favourites'
      preLoaderRoute: typeof SettingsFavouritesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/channel/$handle': {
      id: '/channel/$handle'
      path: '/channel/$handle'
      fullPath: '/channel/$handle'
      preLoaderRoute: typeof ChannelHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsFavouritesRoute: typeof SettingsFavouritesRoute
  SettingsMultistreamRoute: typeof SettingsMultistreamRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsRecommendationsRoute: typeof SettingsRecommendationsRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsFavouritesRoute: SettingsFavouritesRoute,
  SettingsMultistreamRoute: SettingsMultistreamRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsRecommendationsRoute: SettingsRecommendationsRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GoLiveRoute: GoLiveRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ChannelHandleRoute: ChannelHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
